version: '3'
services:
  instagram-frontend:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./node_modules:/instagram-frontend/node_modules
      - ./:/instagram-frontend
    stdin_open: true
    ports:
      - '3000:3000'
